name: admu_recweek_app
description: The official recweek mobile application of Ateneo de Manila University

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  firebase_messaging: ^6.0.16
  alphabet_list_scroll_view: ^1.0.6
  flutter_slidable: ^0.5.4
  url_launcher: ^5.5.0
  fluttertoast: ^7.0.2
  modal_bottom_sheet: ^0.2.0+1
  cloud_firestore: ^0.13.7
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: '^0.7.5'
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  ios: true
  android: true
  image_path_ios: 'assets/images/logo.png'
  image_path_android: 'assets/images/logo.png'

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/bodies/coa/
    - assets/bodies/cop/
    - assets/bodies/lions/
    - assets/bodies/student-groups/
    - assets/orgs/dsc/
    - assets/team/
    - assets/data/
    - assets/orgs/coa/ANALYSIS_AND_DISCOURSE/ADS/
    - assets/orgs/coa/ANALYSIS_AND_DISCOURSE/AEA/
    - assets/orgs/coa/ANALYSIS_AND_DISCOURSE/AEUSS/
    - assets/orgs/coa/ANALYSIS_AND_DISCOURSE/APAIR/
    - assets/orgs/coa/ANALYSIS_AND_DISCOURSE/AStat/
    - assets/orgs/coa/ANALYSIS_AND_DISCOURSE/AteneoEntablado/
    - assets/orgs/coa/ANALYSIS_AND_DISCOURSE/DevSoc/
    - assets/orgs/coa/ANALYSIS_AND_DISCOURSE/The_Ateneo_Assembly/
    - assets/orgs/coa/BUSINESS_CLUSTER/ACTM/
    - assets/orgs/coa/BUSINESS_CLUSTER/AIESEC/
    - assets/orgs/coa/BUSINESS_CLUSTER/AJMA/
    - assets/orgs/coa/BUSINESS_CLUSTER/AMA/
    - assets/orgs/coa/BUSINESS_CLUSTER/Ateneo_BCG/
    - assets/orgs/coa/BUSINESS_CLUSTER/Ateneo_Lex/
    - assets/orgs/coa/BUSINESS_CLUSTER/MACA/
    - assets/orgs/coa/BUSINESS_CLUSTER/MEA/
    - assets/orgs/coa/BUSINESS_CLUSTER/MEcO/
    - assets/orgs/coa/COP/HEIGHTS_Ateneo/
    - assets/orgs/coa/COP/Matanglawin_Ateneo/
    - assets/orgs/coa/COP/The_GUIDON/
    - assets/orgs/coa/FAITH_FORMATION/ACIL/
    - assets/orgs/coa/FAITH_FORMATION/ACLC/
    - assets/orgs/coa/FAITH_FORMATION/ACMG/
    - assets/orgs/coa/FAITH_FORMATION/AtSCA/
    - assets/orgs/coa/FAITH_FORMATION/YFC/
    - assets/orgs/coa/HEALTH_AND_ENVIRONMENT/AESS/
    - assets/orgs/coa/HEALTH_AND_ENVIRONMENT/ISDA/
    - assets/orgs/coa/HEALTH_AND_ENVIRONMENT/LM/
    - assets/orgs/coa/HEALTH_AND_ENVIRONMENT/PEERS/
    - assets/orgs/coa/HEALTH_AND_ENVIRONMENT/ThePMSA/
    - assets/orgs/coa/INTERCULTURAL_RELATIONS/ASEC/
    - assets/orgs/coa/INTERCULTURAL_RELATIONS/ATENEO_HINOMOTO/
    - assets/orgs/coa/INTERCULTURAL_RELATIONS/ATENEO_LINGUA_ARTS_CULTURA/
    - assets/orgs/coa/INTERCULTURAL_RELATIONS/BAYBAYIN_ATENEO/
    - assets/orgs/coa/INTERCULTURAL_RELATIONS/CELADON/
    - assets/orgs/coa/MEDIA_AND_CREATIVES_CLUSTER/ACOMM/
    - assets/orgs/coa/MEDIA_AND_CREATIVES_CLUSTER/AMP/
    - assets/orgs/coa/MEDIA_AND_CREATIVES_CLUSTER/CoSA/
    - assets/orgs/coa/MEDIA_AND_CREATIVES_CLUSTER/LFC/
    - assets/orgs/coa/PERFORMING_ARTS_CLUSTER/ACGC/
    - assets/orgs/coa/PERFORMING_ARTS_CLUSTER/BLUEREP/
    - assets/orgs/coa/PERFORMING_ARTS_CLUSTER/CADS/
    - assets/orgs/coa/PERFORMING_ARTS_CLUSTER/TA/
    - assets/orgs/coa/SCIENCE_AND_TECH/ACHES/
    - assets/orgs/coa/SCIENCE_AND_TECH/AECES/
    - assets/orgs/coa/SCIENCE_AND_TECH/AMS/
    - assets/orgs/coa/SCIENCE_AND_TECH/ATENEO_PSYCHE/
    - assets/orgs/coa/SCIENCE_AND_TECH/BOX/
    - assets/orgs/coa/SCIENCE_AND_TECH/COMPSAT/
    - assets/orgs/coa/SCIENCE_AND_TECH/LEAPS/
    - assets/orgs/coa/SCIENCE_AND_TECH/MISA/
    - assets/orgs/coa/SECTOR-BASED/Ateneo_CODE/
    - assets/orgs/coa/SECTOR-BASED/Ateneo_EDGE/
    - assets/orgs/coa/SECTOR-BASED/Ateneo_Gabay/
    - assets/orgs/coa/SECTOR-BASED/Ateneo_SPEED/
    - assets/orgs/coa/SECTOR-BASED/Barefoot_Philippines/
    - assets/orgs/coa/SECTOR-BASED/KYTHE/
    - assets/orgs/coa/SECTOR-BASED/Musmos_Ateneo/
    - assets/orgs/coa/STUDENT_GROUPS/AEGIS/
    - assets/orgs/coa/STUDENT_GROUPS/Ateneo_Commission_on_Elections/
    - assets/orgs/coa/STUDENT_GROUPS/DSWS/
    - assets/orgs/coa/STUDENT_GROUPS/LSOPCS/
    - assets/orgs/coa/STUDENT_GROUPS/Office_of_the_Ombudsman/
    - assets/orgs/coa/STUDENT_GROUPS/Sanggu/
    - assets/orgs/coa/STUDENT_GROUPS/SJC/
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
